main:
  - name: Home
    url:
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: Research
    url: research
    weight: 30
  - name: Teaching
    identifier: teaching
    weight: 40
  - name: Courses
    parent: teaching
    url: courses
    weight: 10
  - name: Theses
    parent: teaching
    url: theses
    weight: 20
  - name: News
    url: news
    weight: 50

